export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const GET_CHARACTERS = "GET_CHARACTERS";
export const ADD_CHARACTER = "ADD_CHARACTER";
export const EDIT_CHARACTER = "EDIT_CHARACTER";
export const UPDATE_CHARACTER = "UPDATE_CHARACTER";
export const REMOVE_CHARACTER = "REMOVE_CHARACTER";
export const CLEAR_EDIT = "CLEAR_EDIT";
export const CHARACTERS_ERROR = "CHARACTERS_ERROR";
export const SET_EDIT_MODE = "SET_EDIT_MODE";
